---
- name: install sudo
  apt:
    pkg: sudo
    state: installed
    update_cache: no
    install_recommends: no

- name: deploy /etc/sudoers
  template:
    src: etc/sudoers.j2
    dest: /etc/sudoers
    owner: root
    group: root
    mode: 440
