---
- name: Converge
  become: yes
  hosts: all
  vars:
    sudo_user_aliases:
      - "ADMINS = %sudo,%bluadm,%brickadm"
      - "TEST = %sudo,%bluadm,%brickadm"
    sudo_host_aliases:
      - "TEST = localhost"
    sudo_runas_aliases:
      - "ROOT = #0"
    sudo_permissions:
      - "root ALL=(ALL) ALL"
      - "%sudo ALL=(ROOT) NOPASSWD:ALL"
      - "ADMINS ALL=(ALL) NOPASSWD:ALL"
      - "TEST TEST=(ROOT) NOPASSWD:ALL"
  roles:
    - role: role-sudo
